services:
  # postgres-db:
  #   image: postgres:15
  #   # image: pgvector/pgvector:pg16
  #   container_name: data-analyst-db
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASS} 
  #     POSTGRES_DB: ${DB_NAME}
  #   ports:
  #     - "${DB_PORT}:5432"
  #     #- "5434:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  #   # volumes:
  #   #   - ./data:/var/lib/postgresql/data


  grafana:
    image: grafana/grafana:12.3.0
    container_name: grafana
    restart: unless-stopped
    environment: # Estos son los plugins ejemplo a instalar (si ninguno, borrar todo environment)
      - GF_SERVER_ROOT_URL=http://my.grafana.server
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
      #- GF_PLUGINS_PREINSTALL=ae3e-plotly-panel,michaeldmoore-scatter-panel,natel-discrete-panel,vonage-status-panel,jdbranham-diagram-panel,volkovlabs-echarts-panel,yesoreyeram-infinity-datasource,marcusolsson-json-datasource,marcusolsson-csv-datasource,yesoreyeram-boomtable-panel,flant-statusmap-panel
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - './.vols/grafana_storage:/var/lib/grafana'

# en el dir raiz: 
# mkdir -p ./.vols/grafana_storage
# sudo chown -R 472:472 ./.vols/grafana_storage


